/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as StreamingRouteImport } from './routes/streaming'
import { Route as RedirectRouteImport } from './routes/redirect'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as ParallelRouteImport } from './routes/parallel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FileUploadRouteImport } from './routes/file-upload'
import { Route as ErrorDemoRouteImport } from './routes/error-demo'
import { Route as DeferredRouteImport } from './routes/deferred'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomScriptDotjsRouteImport } from './routes/customScript[.]js'
import { Route as PathlessLayoutRouteImport } from './routes/_pathlessLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as UsersNewRouteImport } from './routes/users.new'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as SsrUsersRouteImport } from './routes/ssr.users'
import { Route as PostsInfiniteRouteImport } from './routes/posts.infinite'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as PathlessLayoutNestedLayoutRouteImport } from './routes/_pathlessLayout/_nested-layout'
import { Route as UsersUserIdEditRouteImport } from './routes/users.$userId.edit'
import { Route as PostsPostIdDeepRouteImport } from './routes/posts_.$postId.deep'
import { Route as ApiUsersUserIdRouteImport } from './routes/api/users.$userId'
import { Route as PathlessLayoutNestedLayoutRouteBRouteImport } from './routes/_pathlessLayout/_nested-layout/route-b'
import { Route as PathlessLayoutNestedLayoutRouteARouteImport } from './routes/_pathlessLayout/_nested-layout/route-a'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamingRoute = StreamingRouteImport.update({
  id: '/streaming',
  path: '/streaming',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectRoute = RedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ParallelRoute = ParallelRouteImport.update({
  id: '/parallel',
  path: '/parallel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FileUploadRoute = FileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorDemoRoute = ErrorDemoRouteImport.update({
  id: '/error-demo',
  path: '/error-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DeferredRoute = DeferredRouteImport.update({
  id: '/deferred',
  path: '/deferred',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomScriptDotjsRoute = CustomScriptDotjsRouteImport.update({
  id: '/customScript.js',
  path: '/customScript.js',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutRoute = PathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const UsersNewRoute = UsersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => UsersRoute,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => UsersRoute,
} as any)
const SsrUsersRoute = SsrUsersRouteImport.update({
  id: '/ssr/users',
  path: '/ssr/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsInfiniteRoute = PostsInfiniteRouteImport.update({
  id: '/infinite',
  path: '/infinite',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const PathlessLayoutNestedLayoutRoute =
  PathlessLayoutNestedLayoutRouteImport.update({
    id: '/_nested-layout',
    getParentRoute: () => PathlessLayoutRoute,
  } as any)
const UsersUserIdEditRoute = UsersUserIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => UsersUserIdRoute,
} as any)
const PostsPostIdDeepRoute = PostsPostIdDeepRouteImport.update({
  id: '/posts_/$postId/deep',
  path: '/posts/$postId/deep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUserIdRoute = ApiUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersRoute,
} as any)
const PathlessLayoutNestedLayoutRouteBRoute =
  PathlessLayoutNestedLayoutRouteBRouteImport.update({
    id: '/route-b',
    path: '/route-b',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)
const PathlessLayoutNestedLayoutRouteARoute =
  PathlessLayoutNestedLayoutRouteARouteImport.update({
    id: '/route-a',
    path: '/route-a',
    getParentRoute: () => PathlessLayoutNestedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/error-demo': typeof ErrorDemoRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/streaming': typeof StreamingRoute
  '/users': typeof UsersRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/infinite': typeof PostsInfiniteRoute
  '/ssr/users': typeof SsrUsersRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/error-demo': typeof ErrorDemoRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/redirect': typeof RedirectRoute
  '/streaming': typeof StreamingRoute
  '/api/users': typeof ApiUsersRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/infinite': typeof PostsInfiniteRoute
  '/ssr/users': typeof SsrUsersRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/posts': typeof PostsIndexRoute
  '/users': typeof UsersIndexRoute
  '/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts/$postId/deep': typeof PostsPostIdDeepRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_pathlessLayout': typeof PathlessLayoutRouteWithChildren
  '/customScript.js': typeof CustomScriptDotjsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/deferred': typeof DeferredRoute
  '/error-demo': typeof ErrorDemoRoute
  '/file-upload': typeof FileUploadRoute
  '/login': typeof LoginRoute
  '/parallel': typeof ParallelRoute
  '/posts': typeof PostsRouteWithChildren
  '/redirect': typeof RedirectRoute
  '/streaming': typeof StreamingRoute
  '/users': typeof UsersRouteWithChildren
  '/_pathlessLayout/_nested-layout': typeof PathlessLayoutNestedLayoutRouteWithChildren
  '/api/users': typeof ApiUsersRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/posts/infinite': typeof PostsInfiniteRoute
  '/ssr/users': typeof SsrUsersRoute
  '/users/$userId': typeof UsersUserIdRouteWithChildren
  '/users/new': typeof UsersNewRoute
  '/posts/': typeof PostsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/_pathlessLayout/_nested-layout/route-a': typeof PathlessLayoutNestedLayoutRouteARoute
  '/_pathlessLayout/_nested-layout/route-b': typeof PathlessLayoutNestedLayoutRouteBRoute
  '/api/users/$userId': typeof ApiUsersUserIdRoute
  '/posts_/$postId/deep': typeof PostsPostIdDeepRoute
  '/users/$userId/edit': typeof UsersUserIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customScript.js'
    | '/dashboard'
    | '/deferred'
    | '/error-demo'
    | '/file-upload'
    | '/login'
    | '/parallel'
    | '/posts'
    | '/redirect'
    | '/streaming'
    | '/users'
    | '/api/users'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/posts/$postId'
    | '/posts/infinite'
    | '/ssr/users'
    | '/users/$userId'
    | '/users/new'
    | '/posts/'
    | '/users/'
    | '/route-a'
    | '/route-b'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/users/$userId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customScript.js'
    | '/dashboard'
    | '/deferred'
    | '/error-demo'
    | '/file-upload'
    | '/login'
    | '/parallel'
    | '/redirect'
    | '/streaming'
    | '/api/users'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/posts/$postId'
    | '/posts/infinite'
    | '/ssr/users'
    | '/users/$userId'
    | '/users/new'
    | '/posts'
    | '/users'
    | '/route-a'
    | '/route-b'
    | '/api/users/$userId'
    | '/posts/$postId/deep'
    | '/users/$userId/edit'
  id:
    | '__root__'
    | '/'
    | '/_pathlessLayout'
    | '/customScript.js'
    | '/dashboard'
    | '/deferred'
    | '/error-demo'
    | '/file-upload'
    | '/login'
    | '/parallel'
    | '/posts'
    | '/redirect'
    | '/streaming'
    | '/users'
    | '/_pathlessLayout/_nested-layout'
    | '/api/users'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/posts/$postId'
    | '/posts/infinite'
    | '/ssr/users'
    | '/users/$userId'
    | '/users/new'
    | '/posts/'
    | '/users/'
    | '/_pathlessLayout/_nested-layout/route-a'
    | '/_pathlessLayout/_nested-layout/route-b'
    | '/api/users/$userId'
    | '/posts_/$postId/deep'
    | '/users/$userId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PathlessLayoutRoute: typeof PathlessLayoutRouteWithChildren
  CustomScriptDotjsRoute: typeof CustomScriptDotjsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DeferredRoute: typeof DeferredRoute
  ErrorDemoRoute: typeof ErrorDemoRoute
  FileUploadRoute: typeof FileUploadRoute
  LoginRoute: typeof LoginRoute
  ParallelRoute: typeof ParallelRoute
  PostsRoute: typeof PostsRouteWithChildren
  RedirectRoute: typeof RedirectRoute
  StreamingRoute: typeof StreamingRoute
  UsersRoute: typeof UsersRouteWithChildren
  ApiUsersRoute: typeof ApiUsersRouteWithChildren
  SsrUsersRoute: typeof SsrUsersRoute
  PostsPostIdDeepRoute: typeof PostsPostIdDeepRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaming': {
      id: '/streaming'
      path: '/streaming'
      fullPath: '/streaming'
      preLoaderRoute: typeof StreamingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof RedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parallel': {
      id: '/parallel'
      path: '/parallel'
      fullPath: '/parallel'
      preLoaderRoute: typeof ParallelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file-upload': {
      id: '/file-upload'
      path: '/file-upload'
      fullPath: '/file-upload'
      preLoaderRoute: typeof FileUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-demo': {
      id: '/error-demo'
      path: '/error-demo'
      fullPath: '/error-demo'
      preLoaderRoute: typeof ErrorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deferred': {
      id: '/deferred'
      path: '/deferred'
      fullPath: '/deferred'
      preLoaderRoute: typeof DeferredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customScript.js': {
      id: '/customScript.js'
      path: '/customScript.js'
      fullPath: '/customScript.js'
      preLoaderRoute: typeof CustomScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout': {
      id: '/_pathlessLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/users/new': {
      id: '/users/new'
      path: '/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof UsersNewRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof UsersRoute
    }
    '/ssr/users': {
      id: '/ssr/users'
      path: '/ssr/users'
      fullPath: '/ssr/users'
      preLoaderRoute: typeof SsrUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/infinite': {
      id: '/posts/infinite'
      path: '/infinite'
      fullPath: '/posts/infinite'
      preLoaderRoute: typeof PostsInfiniteRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_pathlessLayout/_nested-layout': {
      id: '/_pathlessLayout/_nested-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteImport
      parentRoute: typeof PathlessLayoutRoute
    }
    '/users/$userId/edit': {
      id: '/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof UsersUserIdEditRouteImport
      parentRoute: typeof UsersUserIdRoute
    }
    '/posts_/$postId/deep': {
      id: '/posts_/$postId/deep'
      path: '/posts/$postId/deep'
      fullPath: '/posts/$postId/deep'
      preLoaderRoute: typeof PostsPostIdDeepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdRouteImport
      parentRoute: typeof ApiUsersRoute
    }
    '/_pathlessLayout/_nested-layout/route-b': {
      id: '/_pathlessLayout/_nested-layout/route-b'
      path: '/route-b'
      fullPath: '/route-b'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteBRouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
    '/_pathlessLayout/_nested-layout/route-a': {
      id: '/_pathlessLayout/_nested-layout/route-a'
      path: '/route-a'
      fullPath: '/route-a'
      preLoaderRoute: typeof PathlessLayoutNestedLayoutRouteARouteImport
      parentRoute: typeof PathlessLayoutNestedLayoutRoute
    }
  }
}

interface PathlessLayoutNestedLayoutRouteChildren {
  PathlessLayoutNestedLayoutRouteARoute: typeof PathlessLayoutNestedLayoutRouteARoute
  PathlessLayoutNestedLayoutRouteBRoute: typeof PathlessLayoutNestedLayoutRouteBRoute
}

const PathlessLayoutNestedLayoutRouteChildren: PathlessLayoutNestedLayoutRouteChildren =
  {
    PathlessLayoutNestedLayoutRouteARoute:
      PathlessLayoutNestedLayoutRouteARoute,
    PathlessLayoutNestedLayoutRouteBRoute:
      PathlessLayoutNestedLayoutRouteBRoute,
  }

const PathlessLayoutNestedLayoutRouteWithChildren =
  PathlessLayoutNestedLayoutRoute._addFileChildren(
    PathlessLayoutNestedLayoutRouteChildren,
  )

interface PathlessLayoutRouteChildren {
  PathlessLayoutNestedLayoutRoute: typeof PathlessLayoutNestedLayoutRouteWithChildren
}

const PathlessLayoutRouteChildren: PathlessLayoutRouteChildren = {
  PathlessLayoutNestedLayoutRoute: PathlessLayoutNestedLayoutRouteWithChildren,
}

const PathlessLayoutRouteWithChildren = PathlessLayoutRoute._addFileChildren(
  PathlessLayoutRouteChildren,
)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsInfiniteRoute: typeof PostsInfiniteRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsInfiniteRoute: PostsInfiniteRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface UsersUserIdRouteChildren {
  UsersUserIdEditRoute: typeof UsersUserIdEditRoute
}

const UsersUserIdRouteChildren: UsersUserIdRouteChildren = {
  UsersUserIdEditRoute: UsersUserIdEditRoute,
}

const UsersUserIdRouteWithChildren = UsersUserIdRoute._addFileChildren(
  UsersUserIdRouteChildren,
)

interface UsersRouteChildren {
  UsersUserIdRoute: typeof UsersUserIdRouteWithChildren
  UsersNewRoute: typeof UsersNewRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersUserIdRoute: UsersUserIdRouteWithChildren,
  UsersNewRoute: UsersNewRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ApiUsersRouteChildren {
  ApiUsersUserIdRoute: typeof ApiUsersUserIdRoute
}

const ApiUsersRouteChildren: ApiUsersRouteChildren = {
  ApiUsersUserIdRoute: ApiUsersUserIdRoute,
}

const ApiUsersRouteWithChildren = ApiUsersRoute._addFileChildren(
  ApiUsersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PathlessLayoutRoute: PathlessLayoutRouteWithChildren,
  CustomScriptDotjsRoute: CustomScriptDotjsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DeferredRoute: DeferredRoute,
  ErrorDemoRoute: ErrorDemoRoute,
  FileUploadRoute: FileUploadRoute,
  LoginRoute: LoginRoute,
  ParallelRoute: ParallelRoute,
  PostsRoute: PostsRouteWithChildren,
  RedirectRoute: RedirectRoute,
  StreamingRoute: StreamingRoute,
  UsersRoute: UsersRouteWithChildren,
  ApiUsersRoute: ApiUsersRouteWithChildren,
  SsrUsersRoute: SsrUsersRoute,
  PostsPostIdDeepRoute: PostsPostIdDeepRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
